version: '3'
services:
  postgres:
    image:
      "postgres:12.0-alpine"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_USER: ${POSTGRES_USER-cards}
      POSTGRES_DB: ${POSTGRES_USER-cards_db}

  selenium:
    image:
      "selenium/standalone-chrome"
    ports:
      - "127.0.0.1:4444:4444"
    environment:
      NODE_MAX_SESSION: 10
      NODE_MAX_INSTANCES: 10
    shm_size: "3gb"

  django:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && gunicorn appointment_assistant_project.wsgi:application --bind 0.0.0.0:8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - selenium
