version: '3'
services:
  postgres:
    image:
      "postgres:12.0-alpine"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_USER: ${POSTGRES_USER-cards}
      POSTGRES_DB: ${POSTGRES_USER-cards_db}

  selenium:
    image:
      "selenium/standalone-chrome"
    ports:
      - "127.0.0.1:4444:4444"
    shm_size: "3gb"

  redis:
    image:
      "redis"
    ports:
      - "0.0.0.0:6379:6379"

  celery:
    build: .
    command: celery -A wildberries_cards_collection worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres

  celery-beat:
    build: .
    command: celery -A wildberries_cards_collection beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres

  django:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py collectstatic --noinput &&  gunicorn appointment_assistant_project.wsgi:application --bind 0.0.0.0:8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - selenium
