# Generated by Django 4.0.4 on 2022-04-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track',
            field=models.ManyToManyField(related_name='products', to='cards.trackparameter', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trackparameter',
            name='time_interval',
            field=models.CharField(choices=[('1 hour', '1 час'), ('12 hours', '12 часов'), ('24 hours', '24 часа')], default='1hour', max_length=10, verbose_name='Интервал отслеживания'),
        ),
    ]
