# Generated by Django 4.0.4 on 2022-04-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_product_track_alter_trackparameter_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='track',
            field=models.ManyToManyField(related_name='products', to='cards.trackparameter', verbose_name='Параметры отслеживания'),
        ),
    ]
