# Generated by Django 4.0.4 on 2022-04-22 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_product_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, help_text='Время отслеживания товара', verbose_name='Конец отслеживания'),
        ),
        migrations.AlterField(
            model_name='trackparameter',
            name='time_interval',
            field=models.CharField(choices=[('1 hour', '1 час'), ('12 hours', '12 часов'), ('24 hours', '24 часа')], default='1 hour', max_length=10, verbose_name='Интервал отслеживания'),
        ),
    ]
